name: JM自动签到

on:
  workflow_dispatch:
  schedule:
    - cron: '20 16 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "18Comic Autosign"
        run: ./function/jm/autosign
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}