name: JM自动签到

on:
  schedule:
    - cron: '20 16 * * *'
  workflow_dispatch:

jobs:
  punch_in:
    runs-on: ubuntu-20.04
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "Punch in"
        run: ./function/jm/autosign
